#!/system/bin/sh

sleep 20

insmod /system/lib/symsearch.ko
insmod /system/lib/modules/cpufreq_conservative.ko
echo conservative > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor

sleep 10

echo 30 > /sys/devices/system/cpu/cpu0/cpufreq/conservative/down_threshold
echo 25 > /sys/devices/system/cpu/cpu0/cpufreq/conservative/freq_step
echo 80000 > /sys/devices/system/cpu/cpu0/cpufreq/conservative/sampling_rate
echo 1 > /sys/devices/system/cpu/cpu0/cpufreq/conservative/ignore_nice_load

exit 0
