#!/system/bin/sh

# enable crond
# crond calls getpwnam (user database search)
echo "root:x:0:0::data/cron:/system/xbin/bash" > /system/etc/passwd
mount -o remount,rw rootfs /
ln -s /system/xbin /xbin
mount -o remount,ro rootfs /
timezone='date +%z'
	if [ $timezone = "0800" ]; then
	TZ=PST8PDT
	elif [ $timezone = "-0700" ]; then
	TZ=MST7MDT
	elif [ $timezone = "-0600" ]; then
	TZ=CST6CDT
	elif [ $timezone = "-0500" ]; then
	TZ=EST5EDT
	else TZ=PST8PDT
	fi
export TZ

# use /data/cron, call the crontab file "root"
	if busybox [ ! -d /data/cron ]; then
		busybox mkdir -p /data/cron
		cat > /data/cron/root << EOF
# run-parts
01 * * * * busybox run-parts /system/etc/cron/cron.hourly
02 4 * * * busybox run-parts /system/etc/cron/cron.daily
22 4 * * 0 busybox run-parts /system/etc/cron/cron.weekly
EOF
	fi
	busybox crond -c /data/cron
fi
