#!/system/bin/sh

sleep 20

insmod /system/lib/modules/symsearch.ko
insmod /system/lib/modules/cpufreq_interactivex.ko nr_running_addr=0xc005e844 
echo 'interactivex' > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor 
